const data = [
    {
        id: 1,
        title: "Amazing Fantasy #15",
        portada: "https://i.annihil.us/u/prod/marvel/i/mg/7/00/5d924ca64c787/clean.jpg",
        precio: 3000,
        descripcion: "Entrega número 15 de Amazing Fantasy donde se cuentan varias historias de marvel incluida la aparicion de El Sorprendente Spider-Man por primera vez en los comics contando la historia de como el joven Peter Parker es mordido por una araña que le proporsiona fantasticos poderes que debe aprender a dominar",
        stock: 10,
        categoria: "marvel",
    },
    {
        id: 2,
        title: "Deadpool Kills the Marvel Universe",
        portada: "https://i.annihil.us/u/prod/marvel/i/mg/3/40/5730e351bd592/clean.jpg",
        precio: 2800,
        descripcion: "¿Qué pasaría si todo lo que pensabas que era divertido sobre Deadpool fuera realmente inquietante? ¿Qué pasaría si decidiera matar a todos y todo lo que conforma el Universo Marvel? ¿Y si realmente lo logró? ¿Sería divertido para ti? ¡El mercenario bocazas da un giro a lo retorcido en un cómic de terror como ningún otro!",
        stock: 10,
        categoria: "marvel",
    },
    {
        id: 3,
        title: "Ms. Marvel Volume 1: No Normal",
        portada: "https://i.annihil.us/u/prod/marvel/i/mg/f/e0/59af130256160/clean.jpg",
        precio: 2300,
        descripcion: "Marvel Comics presenta a la nueva Ms. Marvel, ¡la heroína innovadora que se ha convertido en una sensación internacional! Kamala Khan es una chica ordinaria de la ciudad de Jersey, hasta que de repente se ve facultada con dones extraordinarios. Pero, ¿quién es realmente la nueva Ms. Marvel? ¿Adolescente? ¿Musulmán? ¿Inhumano? ¡Descubre cómo conquista el Universo Marvel!",
        stock: 10,
        categoria: "marvel",
    },
    {
        id: 4,
        title: "Hulk: Gray",
        portada: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQ2BGVcCswofkgpy5n8Hsi0mGlZF16n9lP7_zXCSaTdHNEZkeBU",
        precio: 3100,
        descripcion: "Historieta de Hulk en la que escuchamos a Bruce Banner recordar como fueron sus primeros momentos como Hulk, contando algunos secretos y curiosidades que no vimos en el afamado Hulk #1",
        stock: 10,
        categoria: "marvel",
    },
    {
        id: 5,
        title: "Captain America: Trial of Captain America",
        portada: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRJBSUfdkhSK_pvCVSc73V5CHZorsP1hiqKJrwVQkvBD0ChP3DY",
        precio: 3200,
        descripcion: "Bucky Barnes, el antiguo y futuro Soldado de Invierno, tomó el manto del Capitán América después de la aparente muerte de Steve Rogers. ¡Pero ahora Steve ha vuelto, y los dos Caps deben decidir cuál de ellos empuñará el escudo! Como el Gran Director, el Barón Zemo y Sin dificultan la vida de los héroes, Steve asume un nuevo rol como jefe de S.H.I.E.L.D. ¡Y el pasado secreto de Bucky queda expuesto al mundo! ¡Ahora, Steve debe correr para evitar que Bucky sea tragado por un gulag ruso! Pero cuando ocurran tragedias y el Escuadrón Serpiente regrese, ¿Steve tendrá la fuerza para seguir adelante?",
        stock: 10,
        categoria: "marvel",
    },
    {
        id: 6,
        title: "Batman: La Broma Asesina",
        portada: "https://imagessl3.casadellibro.com/a/l/t7/23/9788416660223.jpg",
        precio: 3500,
        descripcion: "La broma asesina relata los orígenes del supervillano más carismático del mundo del cómic, el Joker, y ofrece una inolvidable interpretación sobre la perturbadora relación entre el Hombre Murciélago y su mayor enemigo. Una retorcida historia de locura y perseverancia en la que el Príncipe Payaso del Crimen lleva al límite al Caballero Oscuro y al Comisario Gordon.",
        stock: 10,
        categoria: "dc",
    },
    {
        id: 7,
        title: "Superman Doomsday",
        portada: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRxrdwXEWb3pUW1qS0X3fkctkKKQyBuOJtaBJTiOMZOnDHnYnX",
        precio: 2900,
        descripcion: "Superman viaja al mundo de pesadilla de Apokolips para enfrentarse a Doomsday, la criatura que le costó la vida al Hombre de Acero. Con la ayuda de la misteriosa Waverider que viaja en el tiempo, Superman finalmente descubre la impactante verdad sobre el origen de su mayor enemigo. ¡Y justo cuando cree que el terror finalmente ha terminado, el gigante asesino regresa a la Tierra aún más poderoso que nunca!",
        stock: 10,
        categoria: "dc",
    },
    {
        id: 8,
        title: "Dragon Ball Super #1",
        portada: "https://http2.mlstatic.com/D_NQ_NP_698973-MLA48497302354_122021-O.jpg",
        precio: 3200,
        descripcion: "El tiempo transcurre, desde aquella gran batalla entre Goku y Majin Boo... ¡¡Ahora, en un mundo que recuperó la paz, se aproxima una nueva batalla!! ¿¡Viene este nuevo enemigo desde el Sexto universo!? Una nueva y completa serie de Dragon Ball, en donde un después es escrito, en un proyecto original de Akira Toriyama.",
        stock: 10,
        categoria: "manga",
    },
    {
        id: 9,
        title: "Demon Slayer #1",
        portada: "https://m.media-amazon.com/images/I/81ZNkhqRvVL.jpg",
        precio: 2700,
        descripcion: "En el Japón de la era Taisho, Tanjiro Kamado es un niño bondadoso que se gana la vida vendiendo carbón. Pero su vida pacífica se hace añicos cuando un demonio mata a toda su familia. Su hermana pequeña, Nezuko, es la única superviviente, ¡pero ella misma se ha transformado en un demonio! Tanjiro emprende un peligroso viaje para encontrar la manera de devolver a su hermana a la normalidad y destruir al demonio que arruinó su vida.",
        stock: 10,
        categoria: "manga",
    },
    {
        id: 10,
        title: "Demon Slayer #2",
        portada: "https://m.media-amazon.com/images/I/81PxvdB+vZL.jpg",
        precio: 2800,
        descripcion: "En el Japón de la era Taisho, Tanjiro Kamado es un niño bondadoso que se gana la vida vendiendo carbón. Pero su vida pacífica se hace añicos cuando un demonio mata a toda su familia. Su hermana pequeña, Nezuko, es la única superviviente, ¡pero ella misma se ha transformado en un demonio! Tanjiro emprende un peligroso viaje para encontrar la manera de devolver a su hermana a la normalidad y destruir al demonio que arruinó su vida.",
        stock: 10,
        categoria: "manga",
    },
    {
        id: 11,
        title: "Berserk #1",
        portada: "https://otakuteca.com/images/books/cover/5bc80d3ce44c3.jpg",
        precio: 2500,
        descripcion: "Guts, un ex-mercenario conocido como el Espadachín Negro, y en búsqueda de su venganza. Luego de una tumultuosa infancia, él finalmente encuentra a alguien a quien respeta y en quien puede confiar; y todo se desmorona cuando esta persona le arrebata todo lo importante para él, con el propósito de cumplir sus propios deseos. Ahora, siendo portador de la marca, Guts se encuentra condenado a un destino en el que es implacablemente perseguido por seres demoníacos. Encaminado en una terrible misión llena de desgracia, Guts, armado con una espada gigante y una fuerza monstruosa, no dejará que nada lo detenga,",
        stock: 10,
        categoria: "manga",
    },
    {
        id: 12,
        title: "Silk Vol.0: The Life and Times of Cindy Moon",
        portada: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTrKv7w7XdN1RDq52JOKasDS3WSozwKZIrloUz5ljCSmjoYkekA",
        precio: 3000,
        descripcion: "Cindy Moon salió disparada de su búnker y entró en el Universo Marvel cuando supimos por primera vez que había sido mordida por la misma araña radiactiva del primer arco de AMAZING SPIDER-MAN. Luego salvó la vida de Peter Parker (¡más de una vez!) y atravesó el Spider-Verse junto a Spider-Woman. Ahora, como SILK, Cindy está sola en la ciudad de Nueva York, buscando su pasado, definiendo su propio futuro y atrapando a los malhechores en el camino. Robbie Thompson (escritor de SUPERNATURAL de TV) llena esta nueva historia con su combinación única de travesuras y sensaciones. Con interiores de la futura superestrella Stacey Lee.",
        stock: 10,
        categoria: "marvel",
    },
    {
        id: 13,
        title: "Mi vida escolar pretendiendo ser una persona inútil",
        portada: "https://olympusscanlation.com/wp-content/uploads/2022/08/resource-193x278.png",
        precio: 2500,
        descripcion: "La humanidad descubrió la esencia del alma humana, Edeya, y estaba logrando su materialización. La sociedad se construyó en torno a Edeya, que era invulnerable a las armas convencionales. La humanidad comenzó a poner toda su atención en el poder de combate de Edeya. Park Jinsong, el protagonista, poseía un alma de rango F y un poder de combate de rango F. Tras la introducción de un pobre programa militar en su instituto y el sistema de rangos de Edeya, Park Jinsong se convirtió en uno de los débiles, y sufrió el desprecio de sus compañeros durante 10 años… Sin embargo, en realidad, la Edeya que había despertado era en realidad el rango S “Intento de Matanza Absoluto”. Park Jinsong estaba muy perturbado por el hecho de que la esencia de su alma giraba en torno a la idea de matar a otros, y siguió viviendo su vida pensando en sí mismo como un inútil de rango F. ¿Podrá Park Jinsong, con un alma para matar, controlar su intención de matar y demostrar que no hay rangos para el alma de uno?",
        stock: 10,
        categoria: "manga",
    },
    {
        id: 14,
        title: "Vader - Dark Visions",
        portada: "https://m.media-amazon.com/images/I/51cBxeT6lTL._SX342_SY445_QL70_ML2_.jpg",
        precio: 3000,
        descripcion: "¿Quién es Darth Vader? Ha sido muchas cosas: ejecutor, comandante, destructor. Él es, para muchos en todo el Imperio Galáctico, el último símbolo de poder y miedo. Pero hay quienes han visto al Señor Oscuro bajo una luz diferente. Algunos rincones de la galaxia están tan desesperados que incluso Vader puede ser un caballero de brillante armadura, mientras que para ciertos comandantes imperiales, la ira de Vader es el precio del fracaso. Pero, ¿cómo es perder el corazón por un Lord Sith, y qué destino le espera al amante desafortunado que se ha enamorado de un hombre tan inalcanzable? Además, aprende cómo se siente ser un piloto de X-wing enfrentándose cara a cara con el TIE Fighter de Vader, ¡y descubre más de los muchos lados del villano más grande de la galaxia!",
        stock: 10,
        categoria: "ciencia-ficcion",
    },
    {
        id: 15,
        title: "Lookism",
        portada: "https://upload.wikimedia.org/wikipedia/en/thumb/1/17/Lookism_Volume_1_Cover.jpg/220px-Lookism_Volume_1_Cover.jpg",
        precio: 2500,
        descripcion: "Daniel Park, o Park Hyung Suk, es un estudiante de secundaria impopular, gordo y feo que es intimidado y despreciado. Constantemente intimidado y acosado todos los días por Logan Lee, a menudo saca su enojo verbalmente contra su madre. Decidido a huir de sus problemas actuales y comenzar de nuevo, se muda a Seúl y asiste a una nueva escuela secundaria. Sin embargo, una noche durante las vacaciones, obtiene un nuevo cuerpo alto, musculoso y muy guapo. También se da cuenta de que al dormir en un cuerpo, despierta en el otro, y que no importa si lleva 24 horas seguidas despierto, siempre se siente descansado en el cuerpo que ocupa.",
        stock: 10,
        categoria: "manga",
    },
    {
        id: 16,
        title: "Robins: Being Robin",
        portada: "http://d3ugyf2ht6aenh.cloudfront.net/stores/947/716/products/64867701-31a5ad60b1834ded1616630068212076-640-0.jpg",
        precio: 3400,
        descripcion: "Los cinco héroes que se pusieron la capa y la máscara de Robin se encuentran en una encrucijada en sus vidas. Dick Grayson, Jason Todd, Tim Drake, Stephanie Brown y Damian Wayne se reúnen para discutir el gran tema que los une: ¿Ser Robin y el compañero de Batman fue la mejor elección que pudieron haber hecho? Pero antes de que puedan llegar al meollo del asunto, son emboscados por un asaltante desconocido con un hueso para recoger con ellos. Ella afirma haber sido el primer Robin, y quiere demostrar que Batman nunca debería haber entrenado a ninguno de ellos. Recopila Robins # 1-6, el ganador del torneo Round Robin 2021 de DC, ¡según lo elegido por ustedes, los lectores!",
        stock: 10,
        categoria: "dc",
    },
    {
        id: 17,
        title: "Star Wars: War Of The Bounty Hunters",
        portada: "https://i2.wp.com/www.tomosygrapas.com/wp-content/uploads/2021/02/Star-Wars-War-of-the-bounty-Hunters.jpg?w=370&h=561&crop&ssl=1",
        precio: 3000,
        descripcion: "¡El evento cómico de Star Wars que estabas esperando! El famoso cazarrecompensas Boba Fett finalmente consiguió su mayor premio: Han Solo, congelado en carbonita para facilitar su transporte. Fett llevará al contrabandista a Tatooine para recoger la enorme recompensa que el temible señor del crimen Jabba the Hutt ha puesto por la cabeza de Solo. Suena fácil. ¿Qué puede salir mal? Solo hay un problema entre Fett y el día de pago... y es uno grande. ¡Pero Fett no se detendrá ante nada para hacer el trabajo! ¡Prepárate para un evento épico alucinante y devastador como ningún otro!",
        stock: 10,
        categoria: "ciencia-ficcion",
    },
    {
        id: 18,
        title: "Jungle Juice",
        portada: "https://img.novelcool.com/logo/202202/a7/Zumo_De_La_Selva8887.jpg",
        precio: 2500,
        descripcion: "Suchan Jang es un estudiante universitario en la cima de la cadena alimenticia social. Pero bajo la fachada perfecta, esconde un par de alas de insecto que crecieron repentinamente cuando usó un misterioso insecticida llamado «Jugo de Jungla». La vida de Suchan se desmorona cuando revela sus alas al mundo para salvar la vida de alguien. Cuando parece que toda esperanza está perdida, Suchan se topa con un mundo oculto de insectos humanos donde todos son aceptados por lo que son. Pero la ley de la selva rige esta sociedad secreta, y todos deben valerse por sí mismos para sobrevivir.",
        stock: 10,
        categoria: "manga",
    },
    {
        id: 19,
        title: "Naruto Vol.1",
        portada: "https://m.media-amazon.com/images/I/51Y11bNXfTL._SX337_BO1,204,203,200_.jpg",
        precio: 3200,
        descripcion: "En la Villa Oculta de la Hoja, un chaval de lo más problemático que estudia en la escuela de ninjas, Naruto, se dedica a urdir gamberrada tras gamberrada. El sueño de Naruto es el de llegar un día a heredar el nombre de Hokage, reservado a los grandes héroes y de convertirse en el mejor ninja de todos los tiempos. ¡¿Podrá Naruto llegar a cumplir sus anhelos de grandeza?!",
        stock: 10,
        categoria: "manga",
    },
    {
        id: 20,
        title: "La muerte de Superman",
        portada: "https://m.media-amazon.com/images/I/81PcCwX2+RL.jpg",
        precio: 3200,
        descripcion: "En 1992, el mundo se vistió de luto. Superman, el primer superhéroe de la historia, moría a manos de Juicio Final en lo que acabó siendo uno de los cómics más vendidos de la historia. Millones de ejemplares en un solo día confirmaron el interés mediático que levantó esta historia, perteneciente a una campaña de marketing impresionante por parte de DC Comics.",
        stock: 10,
        categoria: "dc",
    },
    {
        id: 21,
        title: "The Final Night",
        portada: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQDcEGn0ROLpNCfmgYkrbhWubGpwD6zucNpJLopX-cUi2VekeYj",
        precio: 3200,
        descripcion: "¿Le tienes miedo a la oscuridad? Los héroes del Universo DC se unen para luchar contra una amenaza aterradora que puede robar la luz y la energía del sol. Sin luz, sin calor. ¿Qué harías si cayera la noche... para siempre?",
        stock: 10,
        categoria: "dc",
    },
    {
        id: 22,
        title: "Flash Forward",
        portada: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcR_Dqmwv4l6WhOXysjcj1MRJigOLacDPxj2CXbVh1aPnEOksOwK",
        precio: 3200,
        descripcion: "Su nombre es Wally West, y fue el hombre vivo más rápido. Es decir, hasta que el Multiverso fue reescrito sin él ni su familia en él. Wally regresó e intentó que funcionara, pero el daño ya estaba hecho. Partiendo de los eventos de Heroes in Crisis, sigue al hombre que se hace llamar Flash en una aventura para encontrar la redención en un cosmos que ha luchado tan duro para destruirlo.",
        stock: 10,
        categoria: "dc",
    },
    {
        id: 23,
        title: "Star Wars: Crimson Empire",
        portada: "https://m.media-amazon.com/images/I/51QCYXCMXRL.jpg",
        precio: 3200,
        descripcion: "Kir Kanos es el último miembro superviviente de la élite de la Guardia Imperial. Está huyendo &mdash; ¡y el Imperio no se detendrá ante nada para destruirlo! Es el poder combinado del Imperio contra un solo hombre. Crimson Empire combina los talentos artísticos dinámicos de las superestrellas de los cómics Paul Gulacy (Batman vs. Predator III) y P. Craig Russell (Elric: Stormbringer) y presenta una nueva portada del ilustrador maestro de Star Wars, Dave Dorman.",
        stock: 10,
        categoria: "ciencia-ficcion",
    },
    {
        id: 24,
        title: "Not All Robots",
        portada: "https://www.panini.es/media/catalog/product/cache/a5b5dd3adfe0d321084804c738f29601/s/c/scnot001_0.jpg",
        precio: 2500,
        descripcion: "Una sátira de ciencia ficción a cargo de Mark Russell (Los 4 Fantásticos: Toda una vida) y Mike Deodato Jr. (El Asombroso Spiderman). En el año 2056, los robots han reemplazado a los seres humanos como fuerza laboral. Da lugar a una coexistencia incómoda entre los nuevos robots inteligentes y los diez mil millones de humanos que viven en la Tierra. A cada familia humana le corresponde un robot del que dependen completamente. ¿Qué podría salir mal? Te presentamos a los Walters, una familia humana cuyo robot, Razorball, pasa su tiempo libre en el garaje trabajando en máquinas diseñadas para matarlos.",
        stock: 10,
        categoria: "ciencia-ficcion",
    },
    {
        id: 25,
        title: "Steampunk Battlestar Galactica 1880",
        portada: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTf6deXwUWBhN5Cgdy7XYCzZWOY0NsVEDLXA3-m7DWkxysT3hr4",
        precio: 2800,
        descripcion: "Cuando el mundo colonial de Caprica es destruido por el ejército mecánico de ciclónicos que pisotean ciudades del profesor Baltar, el archiduque Adama de la Aethership Galactica toma los cielos... eligiendo la supervivencia de la raza humana sobre el rescate de su hijo cautivo, Apolo. Desobedeciendo órdenes y actuando por su cuenta, Lady Athena busca liberar a su hermano secuestrado con la ayuda del piloto fugitivo, el Capitán Starbuck, y su copiloto humanoide Daggit, Muffit... ¡si tan solo pudieran resistir un ataque de los vengativos Piratas del Cielo! ¿Soportarán las naves acorazadas y los audaces viajeros espaciales de este universo Steampunk la amenaza mecánica de los ciclónicos?",
        stock: 10,
        categoria: "ciencia-ficcion",
    },
    {
        id: 26,
        title: "We Stand on Guard",
        portada: "https://books.google.com.ar/books/publisher/content?id=B5ofDgAAQBAJ&pg=PP1&img=1&zoom=3&hl=en&sig=ACfU3U2JOe-UtoG7M6Nb4YpXfyqJqOK8lQ&w=1280",
        precio: 2800,
        descripcion: "Dentro de 100 años, una heróica banda de civiles canadienses deben defender sus hogares después de que los Estados Unidos los invadan. Una batalla superdetallada entre fantásticos luchadores por la libertad y unos robots condenadamente gigantes. El dibujante es STEVE SKROCE, autor estrella en los años 90 de Spiderman. Tan bueno en su nivel de detalle y narrativa que dejó el mundo del cómic porque Hollywood llamó a su puerta. Se encargó, de entre otros storyboards, de la trilogía Matrix. Ha vuelto al mundo del cómic sólo para colaborar con Vaughan y sólo para esta miniserie.",
        stock: 10,
        categoria: "ciencia-ficcion",
    },
    {
        id: 27,
        title: "Star Wars: Obi-Wan and Anakin",
        portada: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTi0twfzHlsw9mzwnouP4-wvgVrdDr_uIKv6VbFmjbe5eJI-6CW",
        precio: 3000,
        descripcion: "Antes de su heroísmo militar en las Guerras Clon, antes de su trágica batalla en Mustafar y muchas décadas antes de su enfrentamiento final en la Estrella de la Muerte, fueron el Maestro Obi-Wan Kenobi y su joven padawan, Anakin Skywalker. Ahora únase a ellos unos años después del entrenamiento del elegido Anakin. Maestro y alumno se han acercado más con el tiempo, pero ha sido un camino difícil. Y las cosas no van a ser más fáciles. De hecho, cuando son llamados a un planeta remoto en busca de ayuda, la pareja puede verse empujada al punto de ruptura. Mientras se encuentran varados en un mundo extraño de tecnología primitiva y nativos mortales, ¿serán capaces de salvarse a sí mismos? Primero deben saber quién pidió ayuda... ¡y por qué!",
        stock: 10,
        categoria: "ciencia-ficcion",
    },
]

export function getComics(){
    return new Promise((resolve) => {
        setTimeout(() => resolve(data), 2000)
    })
}

export function getUnComic(idParams) {
    return new Promise((resolve) => {
        let comicReq = data.find( (comic) => {
            return comic.id === Number(idParams)
        })
        setTimeout(() => resolve(comicReq), 2000)
    })
}

export function getComicsByCategory(categoryId) {
    return new Promise((resolve) => {
        let filterComics = data.filter( item => item.categoria === categoryId)
        setTimeout(() => resolve(filterComics), 2000)
    })
}
